#check Nat.mul_sub_right_distrib
#check Nat.mul_sub_left_distrib
#check Nat.sub_mul
#check Nat.div_lt_iff_lt_mul
#check Nat.div_lt_of_lt_mul
#check Nat.mul_div_cancel
#check Nat.div_mul_cancel
#check Nat.add_mul_mod_self_left
#check Nat.add_mul_mod_self_right
#check Nat.le_mul_of_pos_right
#check Nat.pow_pos
#check Nat.pow_add
#check Nat.pow_le_pow_right
#check Nat.pow_lt_pow_right
#check Nat.mod_self
#check Nat.mod_zero
#check Nat.dvd_of_mod_eq_zero
#check Nat.mul_mod_right
#check Nat.mul_div_right
